# _config.yml

title: "Matheus Borges"  # Título do seu portfólio
email: "matheusandradeborges@exemplo.com"  # (opcional) Seu e-mail, se desejar adicionar
description: "Portfólio de Matheus Borges - Cientista de Dados"  # Descrição do site
baseurl: ""  # Geralmente vazio para repositórios GitHub Pages, caso contrário, use "/nome-do-repositorio"
url: "https://mathborges88.github.io"  # URL do seu site

# Tema
theme: jekyll-theme-merlot # Tema oficial do GitHub Pages

# Exemplo de personalização do tema, se necessário
# logo: "/assets/images/logo.png"  # Caminho para uma imagem de logo, se houver
# favicon: "/assets/images/favicon.ico"  # Caminho para um favicon, se houver

# Plugins (opcional, apenas se necessário)
plugins:
  - jekyll-include-cache

# Outras configurações personalizáveis (opcional)
markdown: kramdown
highlighter: rouge

