# _config.yml

title: "Matheus Borges"  # Título do seu portfólio
email: "matheusandradeborges@exemplo.com"  # (opcional) Seu e-mail, se desejar adicionar
description: "Portfólio de Matheus Borges - Cientista de Dados"  # Descrição do site
baseurl: ""  # Geralmente vazio para repositórios GitHub Pages, caso contrário, use "/nome-do-repositorio"
url: "https://mathborges88.github.io"  # URL do seu site

# Tema
theme: slate 


# Outras configurações personalizáveis (opcional)
markdown: kramdown
highlighter: rouge

